### ISSUE TITLE
Request: Add discussions in this repository

### ISSUE THREAD

**Issue by 0xJWLabs** [DanWlker/toolbox.nvim#1]
I would like to propose an idea to add discussions to this repository, so people can discuss about this. Btw maybe for visual mode is by getting visual selection? What do you think about that?

**Comment by DanWlker** [comment]
Hi thank you for the suggestions. I don't think currently (and in the near future) it will reach a size that it warrants opening discussions, as it is a relatively simple project. I'll consider it when we reach that size, for now Issues will suffice. 

For visual selection I've implemented it with string executions, for functions I think its better to let the user get the selections from nvim's built in implementations (unless there's an edge case that requires defining a function signature that all functions adhere to)

**Comment by DanWlker** [comment]
> Hi thank you for the suggestions. I don't think currently (and in the near future) it will reach a size that it warrants opening discussions, as it is a relatively simple project. I'll consider it when we reach that size, for now Issues will suffice.
> 
> For visual selection I've implemented it with string executions, for functions I think its better to let the user get the selections from nvim's built in implementations (unless there's an edge case that requires defining a function signature that all functions must adhere to)
