### ISSUE TITLE
Add condition function to filter commands

### ISSUE THREAD

**Issue by fpohtmeh** [DanWlker/toolbox.nvim#14]
# Backround
Some commands aren't applicable for some file types or some Vim modes. For example:
- Sort JSON command for Lua buffer
- Copy selection for the normal mode
- Run git command for not versioned directory

# Proposal
Make the commands list more flexible. Decide which command should be displayed before the picker opening.
Pseudocode:
```lua
opts = {
  commands = {
    { name = "Copy selection", execute = ":y", tags = { "Editor"}, modes = { "v" } },
    { name = "Sort JSON", execute = ":%!jq", tags = { "Editor" }, filetypes = { "json" } },
  },
  filter = function(command)
   -- If command filetypes contains json and buffer isn't json, then return false
   -- If the current mode is normal, then "Copy selection" should be hidden. Thus, the function returns false
   return true
  end
}
```

The command list should be re-filtered on the picker opening.

# Note
This functionality can replace the property `tags`
```lua
local current_tags = nil

-- Configuration
opts = {
  filter = function(command)
    -- function takes current_tags into account
  end
}

-- Usage
current_tags = { "git" }
require("toolbox").open_picker()
current_tags = { "json" }
require("toolbox").open_picker()
current_tags = nil -- or {}
require("toolbox").open_picker()
```

**Comment by DanWlker** [comment]
I will consider this, "tags" can accomplish the same thing by applying the checks when invoking the keymaps. So this is more of

sorting every time
vs
having a map to store all tags and displaying the proper tags

I am leaning towards the second one. If you can give a reason for why this is better, or some scenarios that tags don't cover it will help. Thanks

**Comment by fpohtmeh** [comment]
Tags are a good idea. It works for you, but other users may like to define different properties for the filtering.

With the `filter` function, users may open tags-based commands and commands with other properties in common.
It will be possible to filter by complex conditions!

I'll provide a PR with more scenarios

**Comment by DanWlker** [comment]
Sure, if there are valid scenarios where tags cannot work I'll be happy to accept the PR, looking forward to it. Thanks!

Keep in mind for most cases, tags allow the same logic to be done when defining the keymaps as well
