### ISSUE TITLE
Move arguments from withArgs to the run

### ISSUE THREAD

**Issue by fpohtmeh** [DanWlker/toolbox.nvim#16]
![image](https://github.com/user-attachments/assets/eb6393e8-4e61-4dc5-89cf-08729e0d6b31)
Let's use the following format
```lua
require('toolbox').run_command("Test", 42) -- 1 are required
```
Changes are the following:
- Removing withArgs will simplify the plugin API and related implementation.
- The name `run_command` is better in the scope of the toolbox. Users run a command, not the toolbox itself

**Comment by DanWlker** [comment]
To be honest, this was what i considered doing when i first started designing the api. But run(command).withArgs() is more understandable to me when seeing it in the command line. 

If there is additional feedback that this is not clear, I can change it. `run()` is not intended to be invoked directly by a user. 

So probably will not do this

**Comment by fpohtmeh** [comment]
Is it possible to run that without exposing the method to public API?
At least you can rename withArgs to the Lua-friendly underscored name.

If you keep this method public, `run_command(name, args...)` is better and looks helpful in the plugin.
A user can run the command without opening a toolbox! Why not?

**Comment by fpohtmeh** [comment]
In the current implementation, the return type of `run` complicates the API, and the method looks hacky

**Comment by DanWlker** [comment]
> Is it possible to run that without exposing the method to public API? At least you can rename withArgs to the Lua-friendly underscored name.
> 
> If you keep this method public, `run_command(name, args...)` is better and looks helpful in the plugin. A user can run the command without opening a toolbox! Why not?

hmmm.... I'm probably not going to budge on this, unless i manage to refactor for this to work with both strings and functions. In that case too, I would prefer run('command').with_args() for those that require args rather than combining it together. 

Then again, I am also considering something like https://github.com/DanWlker/toolbox.nvim/issues/10.

**Comment by jmiln** [comment]
It looks like this is how you have it set up to work in your preview gif for the plugin too, so if you're set on doing it with the `withArgs`, you may want to update that

**Comment by DanWlker** [comment]
@jmiln will probably do it after significant changes

**Comment by DanWlker** [comment]
Though.. I am considering flipping the command. For now it I don't have a concrete reason, but somehow it feels right.. I will have to sit on it further

For commands that require args:
`require('toolbox').with_args(...).run('command')`

perhaps prompt users with vim.ui.input if args required? hmm...
Or if we don't flip it, populate the command line if the run command requires args...
Needs consideration

Would need to define how args would be passed to string commands that `require_input`

For commands that don't require args:
`require('toolbox').run('command')` perhaps?

Will think on it

**Comment by DanWlker** [comment]
Another concern is we are checking for is_visual to determine whether we need to feed '<, '> to cmdline, if we expose this to users, the api will need to receive this as well for those that require input, which imo is not a pretty api.

So probably will close this as not planned soon
