### ISSUE TITLE
Make sorting of commands configurable

### ISSUE THREAD

**Issue by fpohtmeh** [DanWlker/toolbox.nvim#2]
I prefer alphabetic ;)
Nice to have the sorting by recent

**Comment by DanWlker** [comment]
I will look into this, but may be a while as i am busy these few days. Thank you for the suggestion

**Comment by DanWlker** [comment]
Implemented in https://github.com/DanWlker/toolbox.nvim/commit/48091f488b8bd273ee6e6076c294aac8875fe556

**Comment by DanWlker** [comment]
Reopening as I found I have the need to pin commands / increase the weightage of certain commands

Considerations:

1. Sort by function
- Most customizable

2. Pin only
- No weightage, just pinning, the pinned ones will be sorted by alphabetical as well

3. Weightage
- Sort by weight numbers, adds a "weightage" variable for configuration

4. A combination of weightage and sort by function?

Need to think about which one is better

**Comment by DanWlker** [comment]
Implemented sorting for commands based on weightage in 1108bfa92fea890315019616df280b623c379d9f, will reopen if there is a need to sort differently for different tags, or if there is a need for sorting by recently used (though i don't think that is a good ux as it will move commands around constantly) will consider exposing a sorting function if there is a need for that

**Comment by DanWlker** [comment]
Tracked in #9

**Comment by fpohtmeh** [comment]
Let me recommend a more flexible implementation of the weight:
- it can be a primitive type or function
- by default, it's a `function(name, execute) return name:upper() end`

Maybe you can use the `sort_key` naming instead of the `weight`

**Comment by DanWlker** [comment]
I'm thinking of doing function sorting in here https://github.com/DanWlker/toolbox.nvim/issues/9

However I don't quite understand how your suggestion would work, the reason weight is an int is it is used for comparison when sorting, specifying it as a function would indicate that we can compare all sorts of things, i.e. int vs string.

Or can you give an example of how it would be used?
