### ISSUE TITLE
Add mode parameter for command

### ISSUE THREAD

**Issue by fpohtmeh** [DanWlker/toolbox.nvim#3]
Add mode parameter for command.
- Normal is the default value.
- `{"n", "v"}` for commands which work in both modes
- Commands are hidden if they aren't supported in the current mode. Or the user gets a notification if he uses a command in the wrong mode. 2nd is better IMO because the user still sees the full list of commands

Reason:
- Some commands make a mess if a visual selection is empty. For example: `sort`

**Comment by DanWlker** [comment]
I thought about this for a while. This is implementable, but I don't think its necessary. 

When you're in visual mode and press `:`, it auto shows visual selection, then you can type in your command. If you don't want a visual selection then you should not select in the first place, and the command should error.

The current behavior now is in line with the default neovim behavior. Therefore I am probably not going to add something that has a different default behavior from what neovim does. It would also have the benefit of being somewhat consistent and easy to debug for the end user.

However, I will keep this open as i think i need some time to think about it as well. 

Thank you for the suggestion.

**Comment by DanWlker** [comment]
You can now do this with the tagging function introduced in c687ad98fdd149873d9f99d61bce1b7baf6e1aa9, just set two keymaps, one for Visual and one for Normal, and specify a different tag for each

It should be roughly the same number of keystrokes to if we only allow specifying modes

**Comment by fpohtmeh** [comment]
Any plans to display tags?

Let me display my current configuration so you can understand how I use that. Feel free to use it for your purposes (README, etc.)
```lua
  opts = {
    commands = {
      -- Git
      { name = "Generate .gitignore | Git", execute = "Gitignore" },
      -- Clipboard
      { name = "Copy full path | Clipboard", execute = ":let @+ = expand('%:p')" },
      { name = "Copy directory path | Clipboard", execute = ":let @+ = expand('%:p:h')" },
      { name = "Copy filename | Clipboard", execute = ":let @+ = expand('%:t')" },
      { name = "Copy relative path | Clipboard", execute = ":let @+ = expand('%:.')" },
      -- Editor
      { name = "Remove empty lines | Editor", execute = ":g/^$/d" },
      { name = "Remove trailing spaces | Editor", execute = ":%s/\\s\\+$//e" },
      { name = "Sort selected lines | Editor", execute = "sort" },
      { name = "Sort selected lines reverse | Editor", execute = "sort!" },
      -- Utils
      { name = "Toggle color highlighter | Utils", execute = "ColorizerToggle" },
      { name = "Create image of code (Silicon) | Utils", execute = "Silicon" },
      -- Lua
      { name = "Toggle overseer debug parser | Lua", execute = ":lua require('overseer').debug_parser()" },
    },
  },

```

**Comment by DanWlker** [comment]
Wow those are some useful commands

Can you describe the behavior you would like to see? I don't quite understand what you mean by displaying tags

**Comment by fpohtmeh** [comment]
In general, it may be super useful to have extra sections inside the list alongside the `name.`
For example, some users want to see the `execute` text. Or tags.

Adding functionality for custom sections may improve the user experience.

In my case, I would like to categorize commands by areas: Utils, Lua, Clipboard, Editor, etc. And highlight them differently.
I can open another PR or create the PR with demo when I have some time

**Comment by DanWlker** [comment]
Yeah sure i am open to PRs, I'll try to look into what you are suggesting as well tomorrow, but keep in mind this should be compatible with vim.ui.select.
